In [9]:
# recorded by hao (2018/03/08)
# rock3.hao@gmail.com
# qinlab.BNU

# training of numpy 01

In [10]:
import numpy as np

# print(help(np.genfromtxt))
wd_ach = np.genfromtxt("./data/data_world_alcohol.txt", delimiter=",", dtype=str)
print(type(wd_ach))
print(wd_ach)

<class 'numpy.ndarray'>
[['Year' 'WHO region' 'Country' 'Beverage Types' 'Display Value']
 ['1986' 'Western Pacific' 'Viet Nam' 'Wine' '0']
 ['1986' 'Americas' 'Uruguay' 'Other' '0.5']
 ...
 ['1987' 'Africa' 'Malawi' 'Other' '0.75']
 ['1989' 'Americas' 'Bahamas' 'Wine' '1.5']
 ['1985' 'Africa' 'Malawi' 'Spirits' '0.31']]


In [11]:
# import pandas as pd

# wd_ach = pd.read_csv("/Users/haolei/Toolbox/scr_hao/Python/Numpy/world_alcohol_new.csv")
# wd_ach.head(6)

In [12]:
# The numpy.array() function can take a list or list of lists as input.
# When we input a list, we get a one-dimensional array as a result:
vect = np.array([5, 10, 15, 20,25,30])
# When we input a list of lists, we get a matrix as a result:
mat_2d = np.array([[5, 10, 15], [20, 25, 30]])
mat_3d = np.array([[[1,2],[4,5]],[[1,2],[4,5]],[[1,2],[4,5]]])

print(vect)
print(mat_2d)
print(mat_3d)

[ 5 10 15 20 25 30]
[[ 5 10 15]
 [20 25 30]]
[[[1 2]
  [4 5]]

 [[1 2]
  [4 5]]

 [[1 2]
  [4 5]]]


In [13]:
# We can use the ndarray.shape property to figure out how many elements are in the array
vect = np.array([5, 10, 15, 20,25,30])
print(vect.shape)
# For matrices, the shape property contains a tuple with 2 elements.
mat_2d = np.array([[5, 10, 15], [20, 25, 30]])
print(mat_2d.shape)

mat_3d = np.array([[[1,2],[4,5]],[[1,2],[4,5]],[[1,2],[4,5]]])
print(mat_3d.shape)

(6,)
(2, 3)
(3, 2, 2)


In [14]:
# Each value in a NumPy array has to have the same data type
# NumPy will automatically figure out an appropriate data type when reading in
#data or converting lists to arrays. 
# You can check the data type of a NumPy array using the dtype property.
numbers_01 = np.array([1, 2, 3, 4])
numbers_02 = np.array([1, 2, 3, 4.0])
numbers_03 = np.array([1, 2, 3, '4'])

print(numbers_01)
print(numbers_02)
print(numbers_03)

print('--------------')

print(numbers_01.dtype)
print(numbers_02.dtype)
print(numbers_03.dtype)

[1 2 3 4]
[1. 2. 3. 4.]
['1' '2' '3' '4']
--------------
int64
float64
<U21


In [15]:
# When NumPy can't convert a value to a numeric data type like float or integer,
# it uses a special nan value that stands for Not a Number
# nan is the missing data
# 1.98600000e+03 is actually 1.986 * 10 ^ 3

In [16]:
wd_ach = np.genfromtxt("./data/data_world_alcohol.txt", delimiter=",", dtype=str, skip_header=1)
print(wd_ach)

[['1986' 'Western Pacific' 'Viet Nam' 'Wine' '0']
 ['1986' 'Americas' 'Uruguay' 'Other' '0.5']
 ['1985' 'Africa' "Cte d'Ivoire" 'Wine' '1.62']
 ...
 ['1987' 'Africa' 'Malawi' 'Other' '0.75']
 ['1989' 'Americas' 'Bahamas' 'Wine' '1.5']
 ['1985' 'Africa' 'Malawi' 'Spirits' '0.31']]


In [17]:
# array start start with [0，0]
array_loc_01 = wd_ach[0,1]
array_loc_02 = wd_ach[2,4]
print(array_loc_01)
print(array_loc_02)

Western Pacific
1.62


In [18]:
vect = np.array([5,10,15,20,25,30])
vect_part = vect[0:3]
print(vect_part)  

[ 5 10 15]


In [19]:
mat_2d = np.array([[5, 10, 15], [20, 25, 30]])
print(mat_2d[:,0])

[ 5 20]


In [20]:
print(mat_2d[:,1:3])

[[10 15]
 [25 30]]


In [21]:
print(mat_2d[0:2,0:2])

[[ 5 10]
 [20 25]]
