In [1]:
# recorded by hao (2018/03/09)
# rock3.hao@gmail.com
# qinlab.BNU

# training of numpy 07

In [2]:
import numpy as np
# 交换矩阵的其中两行
a = np.arange(24).reshape(4,6)
print(a)
print('-------------—----')

a[[0,1]] = a[[1,0]]
print(a)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]
-------------—----
[[ 6  7  8  9 10 11]
 [ 0  1  2  3  4  5]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]


In [3]:
# 找出数组中与给定值最接近的数
z = np.array([[0,1,2,3],[4,5,6,7]])
print(z)

a = 0.1
print(np.abs(z-a).argmin())

[[0 1 2 3]
 [4 5 6 7]]
0


In [4]:
# 判断二维矩阵中有没有一整列数为0？
# help(np.random.randint)
z = np.random.randint(0,3,(3,4))
print(z)
print(z.any(axis=0))

[[0 0 0 1]
 [0 1 1 0]
 [2 0 0 1]]
[ True  True  True  True]


In [5]:
# 生成二维的高斯矩阵
x,y = np.meshgrid(np.linspace(-1,1,6),np.linspace(-1,1,6))
print(x)
print('-------------—----')
print(y)
print('-------------—----')

D = np.sqrt(x**2+y**2)
print(D)
print('-------------—----')

sigma,mu = 1,0
a = np.exp(-(D-mu)**2/(2*sigma**2))
print(a)

[[-1.  -0.6 -0.2  0.2  0.6  1. ]
 [-1.  -0.6 -0.2  0.2  0.6  1. ]
 [-1.  -0.6 -0.2  0.2  0.6  1. ]
 [-1.  -0.6 -0.2  0.2  0.6  1. ]
 [-1.  -0.6 -0.2  0.2  0.6  1. ]
 [-1.  -0.6 -0.2  0.2  0.6  1. ]]
-------------—----
[[-1.  -1.  -1.  -1.  -1.  -1. ]
 [-0.6 -0.6 -0.6 -0.6 -0.6 -0.6]
 [-0.2 -0.2 -0.2 -0.2 -0.2 -0.2]
 [ 0.2  0.2  0.2  0.2  0.2  0.2]
 [ 0.6  0.6  0.6  0.6  0.6  0.6]
 [ 1.   1.   1.   1.   1.   1. ]]
-------------—----
[[1.41421356 1.16619038 1.0198039  1.0198039  1.16619038 1.41421356]
 [1.16619038 0.84852814 0.63245553 0.63245553 0.84852814 1.16619038]
 [1.0198039  0.63245553 0.28284271 0.28284271 0.63245553 1.0198039 ]
 [1.0198039  0.63245553 0.28284271 0.28284271 0.63245553 1.0198039 ]
 [1.16619038 0.84852814 0.63245553 0.63245553 0.84852814 1.16619038]
 [1.41421356 1.16619038 1.0198039  1.0198039  1.16619038 1.41421356]]
-------------—----
[[0.36787944 0.50661699 0.59452055 0.59452055 0.50661699 0.36787944]
 [0.50661699 0.69767633 0.81873075 0.81873075 0.69767633 0.50