In [9]:
# recorded by hao (2018/03/09)
# rock3.hao@gmail.com
# qinlab.BNU

# training of numpy 04

In [10]:
import numpy as np
B = np.arange(3)
print(B)
print(np.exp(B)) # e=2.71828
print(np.sqrt(B))

[0 1 2]
[1.         2.71828183 7.3890561 ]
[0.         1.         1.41421356]


In [11]:
# Return the floor of the input
a = np.floor(10*np.random.random((3,4))) # np.floor 向下取整
print(a)
print(a.shape)
print('-------------')

# Flatten the array
a = a.ravel()
print(a)
print(a.shape)
print('-------------')

a = a.reshape(2,6)
print(a)
print(a.shape)
print('-------------')

print(a.T)
print(a.shape)
print('-------------')

# If a dimension is given as -1 in a reshaping operation,
#the other dimensions are automatically calculated:
a.reshape(3,-1) # -1 = 自动计算该维度

[[8. 6. 9. 8.]
 [0. 9. 7. 1.]
 [4. 6. 6. 4.]]
(3, 4)
-------------
[8. 6. 9. 8. 0. 9. 7. 1. 4. 6. 6. 4.]
(12,)
-------------
[[8. 6. 9. 8. 0. 9.]
 [7. 1. 4. 6. 6. 4.]]
(2, 6)
-------------
[[8. 7.]
 [6. 1.]
 [9. 4.]
 [8. 6.]
 [0. 6.]
 [9. 4.]]
(2, 6)
-------------


array([[8., 6., 9., 8.],
       [0., 9., 7., 1.],
       [4., 6., 6., 4.]])

In [12]:
a = np.floor(10*np.random.random((2,2)))
b = np.floor(10*np.random.random((2,3)))
c = np.floor(10*np.random.random((3,2)))
print(a)
print('---------')

print(b)
print('---------')

print(c)
print('---------')

print(np.hstack((a,b)))

print('---------')
print(np.vstack((a,c)))

[[3. 3.]
 [8. 9.]]
---------
[[1. 9. 7.]
 [9. 5. 6.]]
---------
[[5. 0.]
 [9. 3.]
 [7. 8.]]
---------
[[3. 3. 1. 9. 7.]
 [8. 9. 9. 5. 6.]]
---------
[[3. 3.]
 [8. 9.]
 [5. 0.]
 [9. 3.]
 [7. 8.]]


In [13]:
a = np.floor(10*np.random.random((4,9)))
print(a)
print('---------')
 
print(np.hsplit(a,3)) # hsplit
print('---------')

print(np.hsplit(a,3)[0])
print('---------')

print(np.hsplit(a,(3,4,6)))   # Split a after the third and the fourth column
print('---------')

a = np.floor(10*np.random.random((12,2)))
print(a)
print('---------')

print(np.vsplit(a,3)) # vsplit

[[8. 0. 7. 4. 2. 7. 5. 2. 5.]
 [4. 4. 8. 5. 0. 6. 6. 6. 8.]
 [4. 3. 6. 6. 2. 7. 6. 4. 1.]
 [0. 1. 0. 6. 9. 9. 8. 8. 6.]]
---------
[array([[8., 0., 7.],
       [4., 4., 8.],
       [4., 3., 6.],
       [0., 1., 0.]]), array([[4., 2., 7.],
       [5., 0., 6.],
       [6., 2., 7.],
       [6., 9., 9.]]), array([[5., 2., 5.],
       [6., 6., 8.],
       [6., 4., 1.],
       [8., 8., 6.]])]
---------
[[8. 0. 7.]
 [4. 4. 8.]
 [4. 3. 6.]
 [0. 1. 0.]]
---------
[array([[8., 0., 7.],
       [4., 4., 8.],
       [4., 3., 6.],
       [0., 1., 0.]]), array([[4.],
       [5.],
       [6.],
       [6.]]), array([[2., 7.],
       [0., 6.],
       [2., 7.],
       [9., 9.]]), array([[5., 2., 5.],
       [6., 6., 8.],
       [6., 4., 1.],
       [8., 8., 6.]])]
---------
[[7. 3.]
 [1. 1.]
 [3. 0.]
 [8. 4.]
 [1. 2.]
 [8. 0.]
 [5. 6.]
 [3. 8.]
 [4. 2.]
 [3. 3.]
 [2. 8.]
 [2. 2.]]
---------
[array([[7., 3.],
       [1., 1.],
       [3., 0.],
       [8., 4.]]), array([[1., 2.],
       [8., 0.],
       [5.

In [14]:
#Simple assignments make no copy of array objects or of their data.
a = np.arange(12)
print(a.shape)
print('---------')

b = a
# a and b are two names for the same ndarray object
print(b is a)
print('---------')

b.shape = 3,4
print(b.shape)
print(a.shape)
print('---------')

print(id(a))
print(id(b))

(12,)
---------
True
---------
(3, 4)
(3, 4)
---------
4605530480
4605530480


In [15]:
# The view method creates a new array object that looks at the same data.
a = np.arange(12)

c = a.view()
print(c is a)
print(a)
print(a.shape)
print(c)
print(c.shape)
print('---------')

c.shape = 2,6
print(c.shape)
print(a.shape)
print('---------')

c[0,4] = 1234
print(a)
print(c)

False
[ 0  1  2  3  4  5  6  7  8  9 10 11]
(12,)
[ 0  1  2  3  4  5  6  7  8  9 10 11]
(12,)
---------
(2, 6)
(12,)
---------
[   0    1    2    3 1234    5    6    7    8    9   10   11]
[[   0    1    2    3 1234    5]
 [   6    7    8    9   10   11]]


In [16]:
# The copy method makes a complete copy of the array and its data.
a = np.arange(12)
print(a)
d = a.copy().reshape(2,6)
print(d)
print('---------')

print(d is a)
print('---------')

d[0,3] = 9999
print(d) 
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11]
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]
---------
False
---------
[[   0    1    2 9999    4    5]
 [   6    7    8    9   10   11]]
[ 0  1  2  3  4  5  6  7  8  9 10 11]
