In [17]:
# recorded by hao (2018/03/08)
# rock3.hao@gmail.com
# qinlab.BNU

# training of numpy 03

In [18]:
import numpy as np
vect = np.arange(14)
mat_2d = vect.reshape(2, 7)

print(vect)
print(mat_2d)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13]
[[ 0  1  2  3  4  5  6]
 [ 7  8  9 10 11 12 13]]


In [19]:
mat_2d.shape

(2, 7)

In [20]:
# the number of axes (dimensions) of the array
mat_2d.ndim

2

In [21]:
mat_2d.dtype.name

'int64'

In [22]:
# the total number of elements of the array
mat_2d.size

14

In [23]:
np.zeros((4,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [24]:
np.ones((2,4,3), dtype=np.int64)

array([[[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]]])

In [25]:
# To create sequences of numbers
np.arange(10, 30, 5)

array([10, 15, 20, 25])

In [26]:
np.arange( 0, 2, 0.3 )

array([0. , 0.3, 0.6, 0.9, 1.2, 1.5, 1.8])

In [27]:
np.arange(12).reshape(2,6)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

In [28]:
np.random.random((3,4))

array([[0.26495442, 0.87978871, 0.71893613, 0.76615792],
       [0.71709521, 0.31337101, 0.22379644, 0.17553392],
       [0.43892919, 0.93518576, 0.4219123 , 0.41792525]])

In [29]:
from numpy import pi
np.linspace(0, 2*pi, 20) # low=0, high=2*pi, number = 100

array([0.        , 0.33069396, 0.66138793, 0.99208189, 1.32277585,
       1.65346982, 1.98416378, 2.31485774, 2.64555171, 2.97624567,
       3.30693964, 3.6376336 , 3.96832756, 4.29902153, 4.62971549,
       4.96040945, 5.29110342, 5.62179738, 5.95249134, 6.28318531])

In [30]:
np.sin(np.linspace(0, 2*pi, 20))

array([ 0.00000000e+00,  3.24699469e-01,  6.14212713e-01,  8.37166478e-01,
        9.69400266e-01,  9.96584493e-01,  9.15773327e-01,  7.35723911e-01,
        4.75947393e-01,  1.64594590e-01, -1.64594590e-01, -4.75947393e-01,
       -7.35723911e-01, -9.15773327e-01, -9.96584493e-01, -9.69400266e-01,
       -8.37166478e-01, -6.14212713e-01, -3.24699469e-01, -2.44929360e-16])

In [31]:
# the product operator * operates elementwise in NumPy arrays
a = np.array([20,30,40,50,60])
b = np.arange(5)
print(a) 
print(b)

c = a-b
print(c)
c = c-1
print(c)

print(b**2)
print(a<35)

a[a<35]=1
print(a)

[20 30 40 50 60]
[0 1 2 3 4]
[20 29 38 47 56]
[19 28 37 46 55]
[ 0  1  4  9 16]
[ True  True False False False]
[ 1  1 40 50 60]


In [32]:
# The matrix product can be performed using the dot function or method
A = np.array([[1,1],
               [0,1]])
B = np.array([[2,0],
               [3,4]])
print(A)
print('--------')

print(B)
print('--------')

print(A*B)
print('--------')

print(A.dot(B))
print('--------')
print(np.dot(A, B))
# [[ A(1,1)*B(1,1)+A(1,2)*B(2,1)   A(1,1)*B(1,2)+A(1,2)*B(2,2) ]
# [ A(2,1)*B(1,1)+A(2,2)*B(2,1)    A(2,1)*B(1,2)+A(2,2)*B(2,2) ]]

[[1 1]
 [0 1]]
--------
[[2 0]
 [3 4]]
--------
[[2 0]
 [0 4]]
--------
[[5 4]
 [3 4]]
--------
[[5 4]
 [3 4]]
