In [1]:
# recorded by hao (2018/03/09)
# rock3.hao@gmail.com
# qinlab.BNU

# training of numpy 05

In [2]:
import numpy as np
data = np.sin(np.arange(20)).reshape(5,4)
print(data)
print('-------------')

ind_1 = data.argmax(axis=0) # axis=0 按列寻找最大值, 找到行值
print(ind_1)
print('-------------')

ind_2 = data.argmax(axis=1) # axis=1 按行寻找最大值， 找到列值
print(ind_2)
print('-------------')

print(range(data.shape[0]))

data_max_1 = data[ind_1, range(data.shape[1])]
print(data_max_1)
print('-------------')

data_max_2 = data[range(data.shape[0]), ind_2]
print(data_max_2)


[[ 0.          0.84147098  0.90929743  0.14112001]
 [-0.7568025  -0.95892427 -0.2794155   0.6569866 ]
 [ 0.98935825  0.41211849 -0.54402111 -0.99999021]
 [-0.53657292  0.42016704  0.99060736  0.65028784]
 [-0.28790332 -0.96139749 -0.75098725  0.14987721]]
-------------
[2 0 3 1]
-------------
[2 3 0 2 3]
-------------
range(0, 5)
[0.98935825 0.84147098 0.99060736 0.6569866 ]
-------------
[0.90929743 0.6569866  0.98935825 0.99060736 0.14987721]


In [3]:
a = np.arange(1, 41, 10)
print(a)
print('-------------')

b = np.tile(a, (3, 4)) 
print(b)

[ 1 11 21 31]
-------------
[[ 1 11 21 31  1 11 21 31  1 11 21 31  1 11 21 31]
 [ 1 11 21 31  1 11 21 31  1 11 21 31  1 11 21 31]
 [ 1 11 21 31  1 11 21 31  1 11 21 31  1 11 21 31]]


In [4]:
a = np.arange(0, 41, 10)
print(a)
print('-------------')

b = np.tile(a, (1, 4))
print(b)


[ 0 10 20 30 40]
-------------
[[ 0 10 20 30 40  0 10 20 30 40  0 10 20 30 40  0 10 20 30 40]]


In [5]:
a = np.array([[4, 3, 5], [1, 2, 1]])
print(a)
print('-------------')

b = np.sort(a, axis=1)
print(b)
print('-------------')

b = np.sort(a, axis=0)
print(b)
print('-------------')

a.sort(axis=1)
print(a)
print('-------------')

a = np.array([4, 3, 1, 2])
j = np.argsort(a)
print(a)
print(j)
print(a[j])

[[4 3 5]
 [1 2 1]]
-------------
[[3 4 5]
 [1 1 2]]
-------------
[[1 2 1]
 [4 3 5]]
-------------
[[3 4 5]
 [1 1 2]]
-------------
[4 3 1 2]
[2 3 1 0]
[1 2 3 4]
