In [1]:
# recorded by hao (2018/03/08)
# rock3.hao@gmail.com
# qinlab.BNU

# training of numpy 02

In [2]:
import numpy as np
# It will compare the second value to each element in the vector
# If the values are equal, the Python interpreter returns True; otherwise, it returns False
vect = np.array([5, 10, 15, 20])
vect == 10

array([False,  True, False, False])

In [3]:
mat_2d = np.array([
                   [5, 10, 15], 
                   [20, 25, 30],
                   [25, 40, 45]
                 ])
mat_2d == 25

array([[False, False, False],
       [False,  True, False],
       [ True, False, False]])

In [4]:
# Compares vector to the value 15, 
# which generates a new Boolean vector [False, True, False, False].
# It assigns this result to equal_to_15
vect = np.array([5, 15, 15, 20])
equal_to_15 = (vect == 15)
print(equal_to_15)
print(vect[equal_to_15])

[False  True  True False]
[15 15]


In [5]:
mat_2d = np.array([
                [5, 10, 15], 
                [20, 25, 30],
                [25, 40, 45]
             ])
equal_to_25 = (mat_2d[:,1] == 25)
print(equal_to_25)
print(mat_2d[equal_to_25,:])

[False  True False]
[[20 25 30]]


In [6]:
# We can also perform comparisons with multiple conditions
vect = np.array([5, 10, 15, 20])
equal_to_5and10 = (vect == 10) & (vect == 5)
print(equal_to_5and10)

[False False False False]


In [7]:
vect = np.array([5, 10, 15, 20])
equal_to_5or10 = (vect == 10) | (vect == 5)
print(equal_to_5or10)

[ True  True False False]


In [8]:
vect = np.array([5, 10, 15, 20])
equal_to_5or10 = (vect == 10) | (vect == 5)
vect[equal_to_5or10] = 50
print(vect)

[50 50 15 20]


In [9]:
mat_2d = np.array([
            [5, 10, 15], 
            [20, 25, 30],
            [35, 40, 45]
         ])
equal_to_30 = mat_2d[1,:] == 30
print(equal_to_30)
mat_2d[2,equal_to_30] = 1
print(mat_2d)

[False False  True]
[[ 5 10 15]
 [20 25 30]
 [35 40  1]]


In [10]:
# We can convert the data type of an array with the ndarray.astype() method.
vect = np.array(["1", "2", "3","4.0"])
print(vect.dtype)
print(vect)
      
vect = vect.astype(float)
print(vect.dtype)
print(vect)

<U3
['1' '2' '3' '4.0']
float64
[1. 2. 3. 4.]


In [11]:
vect = np.array([5, 10, 15, 2**64])
print(vect)
print(vect.sum())

[5 10 15 18446744073709551616]
18446744073709551646


In [12]:
# The axis dictates which dimension we perform the operation on 1 means that
#we want to perform the operation on each row, and 0 means on each column
mat_2d = np.array([
                [5, 10, 15], 
                [20, 25, 30],
                [35, 40, 45]
             ])
print(mat_2d.sum(axis=1))

[ 30  75 120]


In [13]:
mat_2d = np.array([
                [5, 10, 15], 
                [20, 25, 30],
                [35, 40, 45]
             ])
print(mat_2d.sum(axis=0))

[60 75 90]


In [14]:
# replace nan value with 0

# print world_alcohol
wd_ach = np.genfromtxt("./data/data_world_alcohol.txt", delimiter=",", dtype=float, skip_header=1)
# print(wd_ach)

# print is_value_empty
is_value_empty = np.isnan(wd_ach[:,4])
# print(is_value_empty)

wd_ach[is_value_empty, 4] = '0'
# print(wd_ach)

ach_consumption = wd_ach[:,4]
# print(ach_consumption)

total_ach = ach_consumption.sum()
print(total_ach)

average_ach = ach_consumption.mean()
print(average_ach)

1137.7800000000002
1.1412036108324977
