In [1]:
# recorded by hao (2018/03/09)
# rock3.hao@gmail.com
# qinlab.BNU

# training of numpy 06

In [2]:
import numpy as np
#1:8*8棋盘矩阵，其中1、3、5、7行&&0、2、4、6列的元素置为1   1 ,3，5，7列&&0,2,4,6行也是1
z = np.zeros((8,8), dtype=int)
print(z)
print('-------------—----')

z[1::2,::2] = 1
z[::2,1::2] = 1
print(z)


[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]]
-------------—----
[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [3]:
#2：min()、max()函数
z = np.random.random((4,6))
zmin,zmax = z.min(),z.max()

print(z)
print('-------------—----')
print(zmin)
print('-------------—----')
print(zmax)

[[0.72354412 0.24653988 0.82440974 0.79280032 0.86720088 0.0388157 ]
 [0.06627749 0.08022946 0.39440201 0.16000858 0.95330484 0.41817679]
 [0.16930843 0.04384611 0.21448768 0.8345991  0.54345987 0.51526599]
 [0.71711766 0.21601391 0.63900253 0.04755376 0.31320703 0.2485686 ]]
-------------—----
0.03881569676859331
-------------—----
0.9533048434264751


In [4]:
#归一化，将矩阵规格化到0～1，即最小的变成0，最大的变成1，最小与最大之间的等比缩放
z = 10*np.random.random((4,6))
print(z)
print('-------------—----')

zmin,zmax = z.min(),z.max()
z = (z-zmin)/(zmax-zmin)
print(z)

[[2.05981215 7.86008981 6.50773571 0.5536507  8.65565956 5.60803207]
 [6.24876859 0.37387324 2.75262794 6.74898426 6.92566133 6.48022522]
 [3.44583073 9.77603683 8.71264231 2.53774878 0.33337837 9.72749237]
 [2.1121734  6.86424425 8.05968276 6.75519914 7.96274971 9.7021    ]]
-------------—----
[[0.18283345 0.79709665 0.65387913 0.02332736 0.88134938 0.55859838]
 [0.6264539  0.0042885  0.25620429 0.67942793 0.69813845 0.65096571]
 [0.32961611 1.         0.88738399 0.23344807 0.         0.99485903]
 [0.18837863 0.69163424 0.81823402 0.6800861  0.80796858 0.99216991]]


In [5]:
#矩阵相加
z = np.zeros((4,6))
print(z)
print('-------------—----')

print(np.arange(6))
print('-------------—----')

z += np.arange(6)
print(z)

[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]
-------------—----
[0 1 2 3 4 5]
-------------—----
[[0. 1. 2. 3. 4. 5.]
 [0. 1. 2. 3. 4. 5.]
 [0. 1. 2. 3. 4. 5.]
 [0. 1. 2. 3. 4. 5.]]


In [6]:
# 生成0~10之间均匀分布的11个数，包括0和10
# help(np.linspace)

z = np.linspace(0,10,4, endpoint=True, retstep=True)
print(z)


(array([ 0.        ,  3.33333333,  6.66666667, 10.        ]), 3.3333333333333335)
